server:
  port: 8080

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: dealin01!
    username: dealin
    url: jdbc:mariadb://dealin.cewz49vcfgmy.us-east-1.rds.amazonaws.com:3306/dealin
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        format_sql: true
        show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jwt:
    secret: dealindealindealindealindealindealindealindealin